
export interface Booking {
  id: number;
  lrNo: string;
  bookingDate: string;
  fromCity: string;
  toCity: string;
  lrType: 'TO BE BILLED' | 'PAID' | 'FOC' | 'TOPAY' | 'TBB';
  sender: string;
  receiver: string;
  itemDescription: string;
  qty: number;
  chgWt: number;
  totalAmount: number;
  status: 'In Stock' | 'In Transit' | 'Cancelled' | 'In HOLD';
}

export const sampleBookings: Booking[] = [
  {
    id: 1,
    lrNo: 'CONGP01',
    bookingDate: '2024-08-01',
    fromCity: 'Nagpur',
    toCity: 'Pune',
    lrType: 'TBB',
    sender: 'NOVA INDUSTERIES',
    receiver: 'MONIKA SALES',
    itemDescription: 'Electronics',
    qty: 10,
    chgWt: 100,
    totalAmount: 5000,
    status: 'In Stock',
  },
  {
    id: 2,
    lrNo: 'COPNQ02',
    bookingDate: '2024-08-01',
    fromCity: 'Pune',
    toCity: 'Mumbai',
    lrType: 'PAID',
    sender: 'MONIKA SALES',
    receiver: 'PARTY NAME1',
    itemDescription: 'Machine Parts',
    qty: 5,
    chgWt: 250,
    totalAmount: 8000,
    status: 'In Stock',
  },
  {
    id: 3,
    lrNo: 'COBOM03',
    bookingDate: '2024-08-02',
    fromCity: 'Mumbai',
    toCity: 'Delhi',
    lrType: 'TOPAY',
    sender: 'PARTY NAME1',
    receiver: 'NOVA INDUSTERIES',
    itemDescription: 'Textiles',
    qty: 100,
    chgWt: 50,
    totalAmount: 12000,
    status: 'In Stock',
  },
  {
    id: 4,
    lrNo: 'CODEL04',
    bookingDate: '2024-08-02',
    fromCity: 'Delhi',
    toCity: 'Nagpur',
    lrType: 'TBB',
    sender: 'NOVA INDUSTERIES',
    receiver: 'PARTY NAME1',
    itemDescription: 'Groceries',
    qty: 200,
    chgWt: 220,
    totalAmount: 7500,
    status: 'In Stock',
  },
  {
    id: 5,
    lrNo: 'CONGP05',
    bookingDate: '2024-08-03',
    fromCity: 'Nagpur',
    toCity: 'Bangalore',
    lrType: 'PAID',
    sender: 'MONIKA SALES',
    receiver: 'NOVA INDUSTERIES',
    itemDescription: 'Furniture',
    qty: 2,
    chgWt: 300,
    totalAmount: 15000,
    status: 'In Stock',
  },
  {
    id: 6,
    lrNo: 'COBLR06',
    bookingDate: '2024-08-03',
    fromCity: 'Bangalore',
    toCity: 'Chennai',
    lrType: 'TOPAY',
    sender: 'PARTY NAME1',
    receiver: 'MONIKA SALES',
    itemDescription: 'Auto Parts',
    qty: 20,
    chgWt: 150,
    totalAmount: 9500,
    status: 'In Stock',
  },
  {
    id: 7,
    lrNo: 'COMAA07',
    bookingDate: '2024-08-04',
    fromCity: 'Chennai',
    toCity: 'Hyderabad',
    lrType: 'TBB',
    sender: 'NOVA INDUSTERIES',
    receiver: 'PARTY NAME1',
    itemDescription: 'Pharmaceuticals',
    qty: 50,
    chgWt: 30,
    totalAmount: 25000,
    status: 'In Stock',
  },
  {
    id: 8,
    lrNo: 'COHYD08',
    bookingDate: '2024-08-04',
    fromCity: 'Hyderabad',
    toCity: 'Kolkata',
    lrType: 'PAID',
    sender: 'MONIKA SALES',
    receiver: 'NOVA INDUSTERIES',
    itemDescription: 'Spices',
    qty: 250,
    chgWt: 250,
    totalAmount: 18000,
    status: 'In Stock',
  },
  {
    id: 9,
    lrNo: 'COCCU09',
    bookingDate: '2024-08-05',
    fromCity: 'Kolkata',
    toCity: 'Guwahati',
    lrType: 'TOPAY',
    sender: 'PARTY NAME1',
    receiver: 'MONIKA SALES',
    itemDescription: 'Books',
    qty: 300,
    chgWt: 100,
    totalAmount: 11000,
    status: 'In Stock',
  },
  {
    id: 10,
    lrNo: 'COGAU10',
    bookingDate: '2024-08-05',
    fromCity: 'Guwahati',
    toCity: 'Nagpur',
    lrType: 'TBB',
    sender: 'NOVA INDUSTERIES',
    receiver: 'MONIKA SALES',
    itemDescription: 'Handicrafts',
    qty: 40,
    chgWt: 40,
    totalAmount: 6000,
    status: 'In Stock',
  },
];
